name: Android CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: 8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build app release
      uses: gradle/gradle-build-action@v1
      with:
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        arguments: assembleDebug
    - name: Upload APK to a release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: app/build/outputs/apk/debug/*.apk
        file_glob: true
        tag: ${{ github.run_number }}-${{ github.run_id }}_${{ github.ref }}
        overwrite: true
        body: ${{ github.event.head_commit.message }}